callcenter/urls.py
# coding=utf-8
""" This file is part of Sektionsportal.
    Sektionsportal is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Sektionsportal is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Sektionsportal.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import url
import callcenter.views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', callcenter.views.select_application, name="select-view"),
    url(r'^callcenter/$', callcenter.views.callcenter_view, name="callcenter-view"),
    url(r'^call-hook/(?P<app>\w+)/$', callcenter.views.call, name="call-hook"),
    url(r'^ajax/status/$', callcenter.views.status_callback, name="status-callback"),
    url(r'^ajax/operators/$', callcenter.views.operators, name="operators"),
    url(r'^ajax/contacts/$', callcenter.views.get_contacts, name="contacts"),
    url(r'^ajax/contact/$', callcenter.views.get_contact_detail, name="contact-detail"),
    url(r'^ajax/contact/block/$', callcenter.views.block_contact, name="block-contact"),
    url(r'^ajax/contact/submit/$', callcenter.views.submit_call, name="submit-call"),
    url(r'^ajax/contact/add-note/$', callcenter.views.add_note, name="add-note"),
]

leads/urls.py
# coding=utf-8
""" This file is part of Sektionsportal.
    Sektionsportal is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Sektionsportal is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Sektionsportal.  If not, see <http://www.gnu.org/licenses/>.
"""
from django.conf.urls import url
import leads.views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', leads.views.form_view, name="form-view"),
    url(r'^(?P<pk>[0-9]+)/data.json$', leads.views.get_status, name="get-status"),
    url(r'^script/(?P<pk>[0-9]+)\.js$', leads.views.script_view, name="form-script"),
    url(r'forms/confirm/(?P<secret>[\w-]+)/$',
        leads.views.confirm_view, name="subscription-confirmation"),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.generic import RedirectView
from django.conf.urls.static import static 
from django.conf.urls.i18n import i18n_patterns
from django.contrib.auth import views as auth_views
import mitglieder.views
import rest_framework.authtoken.views


urlpatterns = i18n_patterns(
    url(r'^mitglieder/', include('mitglieder.urls')),
    url(r'^cc/', include('callcenter.urls')),
    url(r'^ap/', include('leads.urls')),
    url(r'^', admin.site.urls),
    url(r'^advanced_filters/', include('advanced_filters.urls')),
    url(
        r'^password_reset/$',
        auth_views.PasswordResetView.as_view(),
        name='admin_password_reset',
    ),
    url(
        r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    url(
        r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    url(
        r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),

)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns += [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'sms/', mitglieder.views.incoming_sms, name="twilio-incoming"),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^api-token-auth/', rest_framework.authtoken.views.obtain_auth_token),
    url(r'^api/', include('mitglieder.rest')),
]

callcenter/models.py
from django.db import models
from django.contrib.auth.models import Group, User
from mitglieder.models import Member, get_field_class
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
# Create your models here.

class Application(models.Model):
    """Stores token and everything for twilio."""
    groups = models.ManyToManyField(Group) # Access Management
    application_sid = models.CharField(max_length=200, verbose_name=_("Anwendungs SID"))
    account_sid = models.CharField(max_length=200, verbose_name=_("Account SID"))
    auth_token = models.CharField(max_length=200, verbose_name=_("Auth Token"))
    name = models.CharField(max_length=100, verbose_name=_("Name"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Anwendung")
        verbose_name_plural = _("Anwendungen")

class Operator(models.Model):
    application = models.ForeignKey(Application, models.CASCADE, verbose_name=_("Anwendung"))
    online = models.BooleanField(default=False)
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name + '@' + self.application.name

class PhoneNumber(models.Model):
    """Used for handling call forwarding"""
    application = models.ForeignKey(Application, on_delete=models.CASCADE, verbose_name=_("Anwendung"))
    number = models.CharField(max_length=20, blank=True, verbose_name=_("Nummer"))
    forward_to = models.TextField(help_text=_("Mehrere Nummern mit neuer Zeile trennen, max. 10"), blank=True, verbose_name=_("Weiterleitungen"))

    def __str__(self):
        return self.number

    class Meta:
        verbose_name = _("Telefonnummer")
        verbose_name_plural = _("Telefonnummern")

class Call(models.Model):
    """Store calls"""
    incoming = models.BooleanField(verbose_name=_("Eingehend"))
    start = models.DateTimeField(_("Start"))
    end = models.DateTimeField(_("Ende"))
    contact = models.ForeignKey(Member, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_("Kontakt"))
    recording = models.FileField(upload_to='recordings/%Y/%m/%d/', blank=True, verbose_name=_("Aufzeichnung"))
    sid = models.CharField(max_length=100)
    operator = models.ForeignKey(Operator, on_delete=models.CASCADE, blank=True, null=True)
    missed = models.BooleanField(default=False)
    caller = models.CharField(max_length=120, blank=True)
    called = models.CharField(max_length=120, blank=True)
    application = models.ForeignKey(Application, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.caller + '<->' + self.called


    class Meta:
        verbose_name = "Anruf"
        verbose_name_plural = "Anrufe"
        ordering = ('-start', )

class CampaignForm(models.Model):
    """ Store questions and the contacts to be called. """
    name = models.CharField(max_length=100)
    contacts = models.ManyToManyField(Member, through='CampaignContact', verbose_name=_("Kontakte"))
    groups = models.ManyToManyField(Group)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Kampagnen Formular")
        verbose_name_plural = _("Kampagnen Formulare")
        ordering = ['name']

class CampaignContact(models.Model):
    contact = models.ForeignKey(Member, on_delete=models.CASCADE, verbose_name=_("Kontakt"))
    campaign = models.ForeignKey(CampaignForm, on_delete=models.CASCADE, verbose_name=_("Kampagne"))
    calls = models.ManyToManyField(Call, related_name="+", blank=True, verbose_name=_("Anrufe"))
    closed = models.BooleanField(_("Abgeschlossen"))
    locked_until = models.DateTimeField(default=timezone.localtime, verbose_name=_("Blockiert bis"))
    blocked = models.BooleanField(default=False, verbose_name=_("Blockiert"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    closed_at = models.DateTimeField(default=timezone.localtime)

    @property
    def is_locked(self):
        return self.locked_until > timezone.localtime()

    def __str__(self):
        return self.contact.full_name + "@" + self.campaign.name

    def get_answer(self, question):
        if self.answer_set.filter(question=question).exists():
            return self.answer_set.filter(question=question)[0].answer
        return ''

    class Meta:
        verbose_name = _("Kampagnenkontakt")
        verbose_name_plural = _("Kampagnenkontakte")

FORM_INPUT_TYPES = (
    ('forms.DateField', _('Datum')),
    ('forms.TimeField', _('Zeit')),
    ('forms.CharField', _('Text')),
    ('forms.ChoiceField', _('Auswahl')),
    ('forms.MultipleChoiceField', _('Mehrfachauswahl')),
    ('forms.BooleanField', _('Wahrheitswert')),
    ('forms.DecimalField', _('Zahl')),
    ('forms.EmailField', _('E-Mail')),
    ('forms.URLField', _('URL')),
    ('forms.FileField', _('Datei')),
)

WIDGETS = (
    ('forms.PasswordInput', _("Passwort-Widget")),
    ('forms.Textarea', _("Langer Text")),
    ('forms.SelectInput', _("Select-Widget")),
    ('forms.Select', _("Select-Widget")),
    ('forms.SelectMultiple', _("Mehrfach-Select")),
    ('forms.RadioSelect', _("Select-Radio-Widget")),
    ('forms.CheckboxSelectMultiple', _("Multipleselect Checkbox")),
)

def get_widget(widget_str):
    from django import forms
    return eval(widget_str)


class Question(models.Model):
    name = models.CharField(max_length=30, verbose_name=_("Name"))
    form = models.ForeignKey(CampaignForm, on_delete=models.CASCADE, verbose_name=_("Kampagne"))
    input_type = models.CharField(max_length=50, choices=FORM_INPUT_TYPES, verbose_name=_("Typ"))
    label = models.TextField(verbose_name=_("Frage"))
    ordering = models.IntegerField(default=1, verbose_name=_("Sortierung"))
    required = models.BooleanField(_("Benötigt"), default=True)
    initial = models.CharField(_("Default"), blank=True, max_length=300)
    choices = models.TextField(
        _("Auswahl"), blank=True, help_text=_("Eine Option pro Zeile"))
    widget = models.CharField(_("Widget"), blank=True,
                              choices=WIDGETS, max_length=100)

    def src_string(self):
        return self.input_type + '(' + self.argument_string + ')'

    def get_instance(self):
        kwargs = dict()
        kwargs['label'] = self.label
        kwargs['required'] = self.required
        if self.initial:
            kwargs['initial'] = self.initial
        if self.choices:
            kwargs['choices'] = ((s.strip(), s.strip())
                                 for s in self.choices.split('\n'))
        if self.widget:
            kwargs['widget'] = get_widget(self.widget)
        return get_field_class(self.input_type)(**kwargs)

    def __str__(self):
        return self.label

    class Meta:
        ordering = ['form','ordering', 'label']
        verbose_name = _("Frage")
        verbose_name_plural = _("Fragen")

    def __str__(self):
        return self.label

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name=_("Frage"))
    result = models.ForeignKey(CampaignContact, models.CASCADE, verbose_name=_("Kontakt"))
    answer = models.TextField(verbose_name=_("Antwort"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.question.name + " Answer"

    class Meta:
        verbose_name = _("Antwort")
        verbose_name_plural = _("Antworten")

callcenter/forms.py
import os
from datetime import datetime

from django import forms
from django.utils.translation import ugettext as _

class CallForm(forms.Form):
    def __init__(self, *args, **kwargs):
        campaign = kwargs.pop('campaign')
        contact = kwargs.pop('contact', None)
        super(CallForm, self).__init__(*args, **kwargs)
        self.campaign = campaign
        for form_field in campaign.question_set.all():
            self.fields[form_field.name] = form_field.get_instance()

callcenter/templates/callcenter/base.html
{% load staticfiles %}
<!doctype html>
<html lang="de">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        {% include 'admin/custom_js.html' %}
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
        <link href="{% static 'callcenter/phone.png' %}" rel="shortcut icon">

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-xyMU7RufUdPGVOZRrc2z2nRWVWBONzqa0NFctWglHmt5q5ukL22+lvHAqhqsIm3h" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/fh-3.1.4/r-2.2.2/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<style>
div#log, div#missed {
    background-color: black;
    color: white;
    font-family: monospace;
    padding-top: 0.5em;
    height: 160px;
    overflow-y: scroll;
}
div#log p, div#missed p {
    margin-bottom: 0.3em;
}
body {
    max-width: 98%;
    margin: auto;
}
@media only screen and (min-width: 1200px) {
    body {
        max-width: 90%;
    }
}

</style>


<link rel="stylesheet" href="{% static 'callcenter/style.css' %}" >

<script type="text/javascript" src="//media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js"></script>

<title>{{title|default:'Callcenter'}}</title>
    </head>
    <body>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->

        <div class="container-fluid">
            <div class="row">
                {% block body %}

                {% endblock %}
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    </body>
</html>

callcenter/templates/callcenter/call_form.html
{% load bootstrap4 %}
<h3>Fragebogen</h3>
<form action="" method="post" id="call-form" class="mt-4">
{% csrf_token %}
<input type="hidden" name="contact" value="{{contact.pk}}">
{% bootstrap_form form %}
{% buttons %}
<button type="submit" class="btn btn-primary">Absenden</button>
{% endbuttons %}
</form>

<script>
    $('#call-form').submit(function(e){
        $.ajax({
            type: "POST",
            url: "{% url 'submit-call' %}",
            data: $('#call-form').serialize(),
            success: function(data){
                $('#exampleModalLabel').text("Erfolgreich ausgefüllt");
                $('#modal-body').text("Änderungen erfolgreich übermittelt");
                $('#exampleModal').modal();
                $('#contact-container').html('');
                $('#form-container').html('');
            }
        });
        e.preventDefault();
    });
</script>

callcenter/templates/callcenter/callcenter_view.html
{% extends 'callcenter/base.html' %}
{% block body %}
<div class="col-12 mt-3">
    <div id="controls" class="row">
        <div id="info" class="col-lg-4 col-md-4">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="inputGroupSelect01">Nummer</label>
                </div>
                <select id="phone-select" class="custom-select">
                    {% for phone in application.phonenumber_set.all %}
                    <option value="{{phone.number}}">{{phone.number}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="inputGroupSelect01">Status</label>
                </div>
                <select id="own-status-select" class="custom-select">
                    <option value="Online">Online</option>
                    <option value="Offline">Offline</option>
                </select>
            </div>
            <div id="output-selection">
                <label>Ringtone Devices</label>
                <select id="ringtone-devices" multiple></select>
                <label>Speaker Devices</label>
                <select id="speaker-devices" multiple></select><br/>
                <a id="get-devices">Seeing unknown devices?</a>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">&#x1f4f1;
                    </span>
                </div>
                <input class="form-control" id="phone-number" type="text" value="+41" autocomplete="tel" placeholder="+41..." />
                <div class="input-group-append">

                    <button id="button-call" class="btn btn-outline-primary" type="button">
                        <i class="fas fa-phone"></i>
                    </button>
                    <button id="button-hangup" class="btn btn-outline-danger" type="button">
                        <i class="fas fa-phone-slash"></i>
                    </button>
                </div>
            </div>
        </div>
        <div id="call-controls" class="col-lg-2 col-md-2">
            <div id="volume-indicators">
                <label>Mikrofon</label>
                <div id="input-volume"></div>
                <label>Lautsprecher</label>
                <div id="output-volume"></div>
            </div>
        </div>
        <div id="online-status" class="col-md-2 col-lg-2">
            Aktiv:
            <ul>
            </ul>
        </div>
        <div class="col-lg-4 col-md-4">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="nav-missed-tab" data-toggle="tab" href="#nav-missed" role="tab" aria-controls="nav-missed" aria-selected="true">Verpasste Anrufe</a>
                    <a class="nav-item nav-link" id="nav-log-tab" data-toggle="tab" href="#nav-log" role="tab" aria-controls="nav-log" aria-selected="false">Log</a>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-missed" role="tabpanel" aria-labelledby="nav-missed-tab">
                    <div id="missed"></div>
                </div>
                <div class="tab-pane fade" id="nav-log" role="tabpanel" aria-labelledby="nav-log-tab">
                    <div id="log"></div>
                </div>
            </div>

        </div>
    </div>
    <hr class="col-12"/>
</div>


<div class="col-12">
    <div class="row">
        <div class="col-lg-3 col-md-4">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="campaign-select">Kampagne</label>
                </div>
                <select name="campaign-select" id="campaign-select" class="custom-select">
                    {% for campaign  in campaigns %}
                    <option value="{{campaign.pk}}">{{campaign.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <label class="input-group-text" for="status-select">Status</label>
                </div>
                <select name="status-select" id="status-select" class="custom-select">
                    <option value="open">Offen</option>
                    <option value="closed">Abgeschlossen</option>
                    <option value="blocked">Blockiert</option>
                    <option value="all">All</option>
                </select>
            </div>
            <div class="my-2" id="stats">Loading...</div>
            <div class="contact-list" id="contact-list">
                <table id="contact-table" class="table table-sm" style="width:100%;"> 
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>#</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="col-lg-4 col-md-8">
            <div id="contact-container">
            </div>
        </div>
        <div class="col-lg-5 col-md-12">
            <div id="form-container">
            </div>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Schliessen</button>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function() {
        var table = $('#contact-table').DataTable( {
            "dom": 'lftp',
            "pagingType": 'numbers',
            "ajax": {
                "url": "{% url 'contacts' %}",
                "type": "POST",
                "data": function(d){
                    return $.extend({}, d, {
                        "campaign": $('#campaign-select').val(),
                        "status": $('#status-select').val(),
                        "csrfmiddlewaretoken": '{{ csrf_token }}',
                        'StartTime': '{% now "c" %}',
                        "Application": '{{application.pk}}'
                    });
                }
            },
            "columns": [
                { "data": "last_name",
                  "render": function(data, type, row, meta){
                      if(type=='display'){
                          return row.first_name + ' ' + row.last_name;
                      }
                  return row.last_name+';' + row.first_name + ";" + row.phone_priv + ";" + row.phone_busi + ";" + row.phone_mobi.replace(' ', '');
                  }
                },
                { 
                    "data": "campaigncontact__pk",
                    "render": function(data, type, row, meta){
                        if(type!='display'){
                            return row.campaigncontact__closed ? 'closed':'open';
                        }
                        return '<button class="btn mt-1 btn-primary"><i class="fas fa-arrow-alt-from-left"></i></button>';
                    }
                }
            ]
        } );

        $('#contact-table tbody').on( 'click', 'button', function () {
            var data = table.row( $(this).parents('tr') ).data();
            var post_data = {
                'contact': data.campaigncontact__pk,
                "csrfmiddlewaretoken": '{{ csrf_token }}'
            };
            // Fetch contact-data and display form
            $.post("{% url 'contact-detail' %}", post_data, function(data){
                if(data.status == 'ok'){
                    $('#form-container').html(data.form);
                    $('#contact-container').html(data.contact_info);
                } else {

                }
            });

        } );

        setInterval( function () {
            table.ajax.reload(function(data){
            var operators = data['operators'];
            var str = ''
            for(var i = 0; i < operators.length; i++){
                s = operators[i].online ? 'online' : 'offline';
                str += '<li class=' + s +  '">' + operators[i].name + '</li>';
            }
            $('#online-status > ul').html(str);

            var missed_calls = data['missed'];
            var str = ''
            for(var i = 0; i < missed_calls.length; i++){
                var call = missed_calls[i];
                var a_string = '<a href="#" onclick="fill_input(\'' +
                      call.caller + '\')">' + call.caller + '</a>';
                str += '<p>[' + call.start + ']:<br> ' + a_string + " --> " + call.called + '</p>';
            }
            $('#missed').html(str);
            $('#stats').text(data.status);
            }, false);

        }, 1000 );
        $('#campaign-select').on('change', function(){
            table.ajax.reload(null, true);
        });

        $('#status-select').on('change', function(){
            table.ajax.reload(null, true);
        });

        $('#own-status-select').on('change', function(){
            var data = {
                Event: $(this).val(),
                App: '{{application.pk}}',
                Operator: '{{operator.pk}}',
                csrfmiddlewaretoken: '{{ csrf_token }}'
            }
            $.post("{% url 'status-callback' %}", data, function(data){
            });

        });
    } );
function dismissChangeRelatedObjectPopup(w, v, o, nv){
    w.close();
    refresh();
}

</script>

<script type="text/javascript" src="//media.twiliocdn.com/sdk/js/client/v1.4/twilio.min.js"></script>
{% include 'callcenter/lookup_script.js' %}

{% endblock %}

callcenter/templates/callcenter/render_phone.html
{% if number %}
<div class="input-group mb-3">
  <div class="input-group-prepend">
      <button onclick="call_twilio('{{number}}');" class="btn btn-outline-primary" type="button" id="button-addon1">
          <i class="fas fa-phone"></i>
      </button>
  </div>
  <input type="text" class="form-control" aria-describedby="basic-addon1" value="{{number}}" readonly>
  {% if whatsapp %}
  <div class="input-group-append">
      <a href="https://web.whatsapp.com/send?phone={{whatsapp}}" class="btn btn-outline-success" target="_blank" >
          <i class="fab fa-whatsapp"></i>
      </a>
  </div>
  {% endif %}
</div>
{% endif %}

callcenter/templates/callcenter/select_application.html
{% extends 'callcenter/base.html' %}

{% block body %}
<div class="application mx-auto my-auto align-middle">
    <form method="post" action="{% url 'callcenter-view' %}">
        {% csrf_token %}
        <div class="input-group mb-3 mt-5">
            <div class="input-group-prepend">
                <label class="input-group-text" for="inputGroupSelect01">Applikation</label>
            </div>
            <select name="app" class="custom-select">
                {% for app in applications %}
                <option value="{{app.pk}}">{{app.name}}</option>
                {% endfor %}
            </select>
            <div class="input-group-append">
                <button class="btn btn-outline-primary" type="submit">Bestätigen</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}